// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/test_schema.proto

package com.example.test_plugin.proto;

public final class TestSchema {
  private TestSchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code com.example.test_plugin.MethodChannelName}
   */
  public enum MethodChannelName
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>TEST_PLUGIN = 0;</code>
     */
    TEST_PLUGIN(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TEST_PLUGIN = 0;</code>
     */
    public static final int TEST_PLUGIN_VALUE = 0;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MethodChannelName valueOf(int value) {
      return forNumber(value);
    }

    public static MethodChannelName forNumber(int value) {
      switch (value) {
        case 0: return TEST_PLUGIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MethodChannelName>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MethodChannelName> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MethodChannelName>() {
            @java.lang.Override
            public MethodChannelName findValueByNumber(int number) {
              return MethodChannelName.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return MethodChannelNameVerifier.INSTANCE;
    }

    private static final class MethodChannelNameVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new MethodChannelNameVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return MethodChannelName.forNumber(number) != null;
            }
          };

    private final int value;

    private MethodChannelName(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.example.test_plugin.MethodChannelName)
  }

  /**
   * Protobuf enum {@code com.example.test_plugin.MethodChannelCalls}
   */
  public enum MethodChannelCalls
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>GET_PLATFORM_VERSION = 0;</code>
     */
    GET_PLATFORM_VERSION(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GET_PLATFORM_VERSION = 0;</code>
     */
    public static final int GET_PLATFORM_VERSION_VALUE = 0;


    @java.lang.Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MethodChannelCalls valueOf(int value) {
      return forNumber(value);
    }

    public static MethodChannelCalls forNumber(int value) {
      switch (value) {
        case 0: return GET_PLATFORM_VERSION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MethodChannelCalls>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MethodChannelCalls> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MethodChannelCalls>() {
            @java.lang.Override
            public MethodChannelCalls findValueByNumber(int number) {
              return MethodChannelCalls.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return MethodChannelCallsVerifier.INSTANCE;
    }

    private static final class MethodChannelCallsVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new MethodChannelCallsVerifier();
            @java.lang.Override
            public boolean isInRange(int number) {
              return MethodChannelCalls.forNumber(number) != null;
            }
          };

    private final int value;

    private MethodChannelCalls(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.example.test_plugin.MethodChannelCalls)
  }

  public interface PlatformVersionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.test_plugin.PlatformVersionResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string os_name = 1;</code>
     */
    java.lang.String getOsName();
    /**
     * <code>string os_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getOsNameBytes();

    /**
     * <code>int32 os_version = 2;</code>
     */
    int getOsVersion();
  }
  /**
   * Protobuf type {@code com.example.test_plugin.PlatformVersionResponse}
   */
  public  static final class PlatformVersionResponse extends
      com.google.protobuf.GeneratedMessageLite<
          PlatformVersionResponse, PlatformVersionResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:com.example.test_plugin.PlatformVersionResponse)
      PlatformVersionResponseOrBuilder {
    private PlatformVersionResponse() {
      osName_ = "";
    }
    public static final int OS_NAME_FIELD_NUMBER = 1;
    private java.lang.String osName_;
    /**
     * <code>string os_name = 1;</code>
     */
    @java.lang.Override
    public java.lang.String getOsName() {
      return osName_;
    }
    /**
     * <code>string os_name = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOsNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(osName_);
    }
    /**
     * <code>string os_name = 1;</code>
     */
    private void setOsName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      osName_ = value;
    }
    /**
     * <code>string os_name = 1;</code>
     */
    private void clearOsName() {
      
      osName_ = getDefaultInstance().getOsName();
    }
    /**
     * <code>string os_name = 1;</code>
     */
    private void setOsNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      osName_ = value.toStringUtf8();
    }

    public static final int OS_VERSION_FIELD_NUMBER = 2;
    private int osVersion_;
    /**
     * <code>int32 os_version = 2;</code>
     */
    @java.lang.Override
    public int getOsVersion() {
      return osVersion_;
    }
    /**
     * <code>int32 os_version = 2;</code>
     */
    private void setOsVersion(int value) {
      
      osVersion_ = value;
    }
    /**
     * <code>int32 os_version = 2;</code>
     */
    private void clearOsVersion() {
      
      osVersion_ = 0;
    }

    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(com.example.test_plugin.proto.TestSchema.PlatformVersionResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code com.example.test_plugin.PlatformVersionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.example.test_plugin.proto.TestSchema.PlatformVersionResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.test_plugin.PlatformVersionResponse)
        com.example.test_plugin.proto.TestSchema.PlatformVersionResponseOrBuilder {
      // Construct using com.example.test_plugin.proto.TestSchema.PlatformVersionResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string os_name = 1;</code>
       */
      @java.lang.Override
      public java.lang.String getOsName() {
        return instance.getOsName();
      }
      /**
       * <code>string os_name = 1;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getOsNameBytes() {
        return instance.getOsNameBytes();
      }
      /**
       * <code>string os_name = 1;</code>
       */
      public Builder setOsName(
          java.lang.String value) {
        copyOnWrite();
        instance.setOsName(value);
        return this;
      }
      /**
       * <code>string os_name = 1;</code>
       */
      public Builder clearOsName() {
        copyOnWrite();
        instance.clearOsName();
        return this;
      }
      /**
       * <code>string os_name = 1;</code>
       */
      public Builder setOsNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOsNameBytes(value);
        return this;
      }

      /**
       * <code>int32 os_version = 2;</code>
       */
      @java.lang.Override
      public int getOsVersion() {
        return instance.getOsVersion();
      }
      /**
       * <code>int32 os_version = 2;</code>
       */
      public Builder setOsVersion(int value) {
        copyOnWrite();
        instance.setOsVersion(value);
        return this;
      }
      /**
       * <code>int32 os_version = 2;</code>
       */
      public Builder clearOsVersion() {
        copyOnWrite();
        instance.clearOsVersion();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.example.test_plugin.PlatformVersionResponse)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.example.test_plugin.proto.TestSchema.PlatformVersionResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "osName_",
              "osVersion_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<com.example.test_plugin.proto.TestSchema.PlatformVersionResponse> parser = PARSER;
          if (parser == null) {
            synchronized (com.example.test_plugin.proto.TestSchema.PlatformVersionResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.example.test_plugin.proto.TestSchema.PlatformVersionResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:com.example.test_plugin.PlatformVersionResponse)
    private static final com.example.test_plugin.proto.TestSchema.PlatformVersionResponse DEFAULT_INSTANCE;
    static {
      PlatformVersionResponse defaultInstance = new PlatformVersionResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        PlatformVersionResponse.class, defaultInstance);
    }

    public static com.example.test_plugin.proto.TestSchema.PlatformVersionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PlatformVersionResponse> PARSER;

    public static com.google.protobuf.Parser<PlatformVersionResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
